# Generated by Django 3.2.24 on 2025-01-11 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
