# Generated by Django 3.2.24 on 2025-01-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара'),
        ),
    ]
