# Generated by Django 3.2.24 on 2025-01-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, verbose_name='Конечная стоимость товаров'),
        ),
    ]
