# Generated by Django 3.2.24 on 2025-02-03 13:48

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20250116_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Адрес заказчика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=12, validators=[django.core.validators.RegexValidator(message='Телефонный номер должен быть представлен в виде +79999999999 (11 цифр)', regex='^\\+?7?\\d{10}$')]),
            preserve_default=False,
        ),
    ]
