# Generated by Django 3.2.24 on 2025-02-04 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_name_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Телефонный номер должен быть представлен в виде +79999999999 (11 цифр)', regex='^(?:\\+7|8)\\d{10}$')]),
        ),
    ]
