# Generated by Django 3.2.24 on 2024-04-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240402_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_latinica',
            field=models.CharField(default='name', max_length=100, verbose_name='название на латинице'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Человеко-читаемое название'),
        ),
    ]
