# Generated by Django 3.2.24 on 2025-02-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_total_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_rate',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Средний рейтинг'),
        ),
    ]
