# Generated by Django 3.2.24 on 2024-05-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(blank=True, db_index=True, default=1, verbose_name='Количество товара'),
        ),
    ]
