# Generated by Django 3.2.24 on 2024-05-11 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='session',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
