# Generated by Django 3.2.24 on 2024-05-11 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20240511_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
