# Generated by Django 3.2.24 on 2024-05-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_cartitem_cart_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
